name: Run Python code and docstyle linters

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python libs used to check code quality.
        run: python3 -m pip install -r requirements-dev.txt

      - name: Lint Python code by mypy
        run: python -m mypy ./

      - name: Lint Python code by flake8
        run: python -m flake8 ./

      - name: Lint Python code by pylint
        run: python -m pylint *.py

      - name: Lint Python code by bandit
        run: python -m bandit ./

      - name: Lint Python code by pydocstyle
        run: python -m pydocstyle ./
