name: Run Python code and docstyle linters

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python libs used to check code quality.
        run: python3 -m pip install -r requirements-dev.txt

      - name: Lint Python code
        run: |
          python -m mypy ./
          python -m flake8 ./
          python -m pylint *.py
          python -m bandit ./
          python -m pydocstyle ./
